### ISSUE TITLE
Web API documentation improvement

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Book#5]
docs url: https://doc.sitecorepowershell.com/web-api.html

Following example URL
`http://remotesitecore/-/script/v2/master/homeanddescendants?user=admin&password=b`
is no longer valid. 

I know this is an example but someone might get stuck like I did.

value `admin` is no longer valid for pattern in [`WildcardMatch` method](https://github.com/SitecorePowerShell/Console/blob/master/Cognifide.PowerShell/Core/Settings/Authorization/AuthorizationEntry.cs#L65)

I had to provide following user via query string: `sitecore\admin` and this should be default one right now. 

**Note:** Converted from Console [issue](https://github.com/SitecorePowerShell/Console/issues/792).

**Comment by michaellwest** [comment]
Added commit dbffb72 to correct the issue @alan-null . Please let me know if you find anything else.

**Comment by alan-null** [comment]
@michaellwest 
I will. Now everything is fine. Thanks.
